#!/usr/bin/env python
"""
解释为什么不同score_thr会导致高置信度FP数量不同
"""

print("=" * 80)
print("为什么不同score_thr会影响高置信度FP数量？")
print("=" * 80)
print()

print("【关键原因】")
print("-" * 60)
print("匹配算法使用的是 IoU 贪婪匹配，而不是按置信度匹配！")
print()

print("【匹配规则】")
print("-" * 60)
print("1. 对于每张图片，计算所有预测框与GT框之间的IoU")
print("2. 按照 IoU 从高到低排序（注意：不是按置信度！）")
print("3. 贪婪匹配：IoU最高的预测框优先匹配GT")
print("4. 每个GT只能匹配一个预测，每个预测也只能匹配一个GT")
print("5. 未匹配的预测框 = FP，未匹配的GT = FN")
print()

print("【示例场景】")
print("-" * 60)
print("假设某张图片有1个GT目标，有以下3个预测框：")
print()
print("预测框A: score=0.0001, IoU=0.65")
print("预测框B: score=0.8,    IoU=0.60")
print("预测框C: score=0.7,    IoU=0.55")
print()

print("【score_thr=0 的情况】")
print("  1. 所有预测都保留（包括A、B、C）")
print("  2. 按IoU排序: A(0.65) > B(0.60) > C(0.55)")
print("  3. 匹配过程:")
print("     - A匹配GT (IoU=0.65 > 0.5) ✓ → A是TP")
print("     - B尝试匹配GT，但GT已被A占用 ✗ → B是FP (score=0.8)")
print("     - C尝试匹配GT，但GT已被A占用 ✗ → C是FP (score=0.7)")
print("  4. 结果: 2个高置信度FP (B和C)")
print()

print("【score_thr=0.001 的情况】")
print("  1. 只保留置信度>=0.001的预测（B、C保留，A被过滤）")
print("  2. 按IoU排序: B(0.60) > C(0.55)")
print("  3. 匹配过程:")
print("     - B匹配GT (IoU=0.60 > 0.5) ✓ → B是TP")
print("     - C尝试匹配GT，但GT已被B占用 ✗ → C是FP (score=0.7)")
print("  4. 结果: 1个高置信度FP (只有C)")
print()

print("【结论】")
print("-" * 60)
print("虽然 score_thr 不会直接过滤掉高置信度预测（score>0.5），")
print("但会间接影响高置信度FP的数量：")
print()
print("✓ score_thr=0 时:")
print("  - 保留了大量低置信度预测")
print("  - 这些低置信度预测可能因为IoU高而优先匹配GT")
print("  - 导致高置信度预测无法匹配GT，被判定为FP")
print("  → 高置信度FP数量: 567张图片")
print()
print("✓ score_thr=0.001 时:")
print("  - 过滤掉了大量极低置信度预测(<0.001)")
print("  - 高置信度预测有更多机会匹配到GT")
print("  - 被判定为FP的高置信度预测减少")
print("  → 高置信度FP数量: 404张图片")
print()

print("【数据验证】")
print("-" * 60)
print(f"差异: 567 - 404 = 163 张图片")
print(f"说明: 有163张图片在score_thr=0时有高置信度FP，")
print(f"      但在score_thr=0.001时，这些高置信度预测成功匹配了GT（变成TP）")
print()

print("【匹配算法的问题】")
print("-" * 60)
print("❌ 当前算法只考虑IoU，不考虑置信度")
print("   → 低置信度但IoU高的预测会优先匹配")
print()
print("✓ 更合理的做法:")
print("   → 先按置信度排序，再按IoU匹配")
print("   → 或者使用匈牙利算法等全局最优匹配")
print()

print("=" * 80)
print()
print("【建议】")
print("-" * 60)
print("在分析FP时，应该分别统计:")
print("1. score_thr=0.001 的高置信度FP (更准确)")
print("2. 这些FP代表了模型真正的高置信度错误")
print()
print("score_thr=0 的高置信度FP包含了很多")
print("\"被低置信度预测抢占GT导致的FP\"，")
print("这些并不是模型真正的高置信度错误。")
print("=" * 80)
